### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [anhpnguyen/servehtmlfileswithsinatra#1]
:+1: Looks good. One potential point of improvement for the future: I'd like to see a little more consistent indentation in the Ruby files. For example, the `end` on line 4 below is actually closing what the `do` on line 2 is starting. So instead of this:

``` ruby
class MyWebApp < Sinatra::Base
  get '/' do
    send_file "views/index#{ rand(3) + 1 }.html"
      end
end
```

we'll want it to be indented inline the line with the `do`, like this:

``` ruby
class MyWebApp < Sinatra::Base
  get '/' do
    send_file "views/index#{ rand(3) + 1 }.html"
  end
end
```

**Comment by anhpnguyen** [comment]
Thanks for the feedback!

**Comment by anhpnguyen** [comment]
Hi Chris - I have just completed this project
http://codekwondo.herokuapp.com/projects/12. Here's the link to it
https://sinatraproject.herokuapp.com/. Can you give me some feedback if
there's any?

**Comment by chrisvfritz** [comment]
I can't see the code from there, but the end result looks pretty good, except that I am getting a few HTML errors when [running your site through the W3C Validator](http://validator.w3.org/check?uri=https%3A%2F%2Fsinatraproject.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0).

**Comment by anhpnguyen** [comment]
Hi Chris! I have fixed those html errors. Can you check again?

**Comment by chrisvfritz** [comment]
Looking nice! I'd say you're good to submit the project. :smiley:

**Comment by anhpnguyen** [comment]
Thanks!

**Comment by anhpnguyen** [comment]
Hi Chris! I got an alert saying that the GitHub repo has already taken and
it wouldn't let me submit the showcase. What should I do?

**Comment by chrisvfritz** [comment]
Each project has to use a different GitHub repo, so I would create a new copy of the project folder (I recommend having a separate folder for each individual project, even if it builds off a previous project). Then from the command line, you can run:

``` git
git remote rm origin
hub create name-of-your-new-github-repo
git push origin master
```
